### ISSUE TITLE
Immediate schedule generation

### ISSUE THREAD

**Issue by sohelsarder** [OpenSRP/opensrp-server#103]
When a front line (FWA) health worker visit a house and register a household. Then after that registration Opensrp server generate pregnancy surveillance schedule (psrf) after 8 weeks if it finds a eligible couple in that household registration. But the workers want to complete the surveillance in a day they are doing household registration to minimize visit and as well as reduce delay in surveillance. Which is very pragmatic case and they want to get immediate schedule support from opensrp. 

One solution we can think of reduce schedule definition window to 0/1 day but  that really not work because of immediate generated schedule trigger by motech once in a day that can't save next day another visit requirement to that particular household.

**Comment by proshantokuet** [comment]
This issue is now solved.
The way of solution : Schedule data comes from Action document of couch-db. MotechListener event save schedule  in Action document by Motech Event. Motech event triggered once in a day in predefined time. So immediate schedule generation was not possible. Now i have saved schedule data with due status to Action document when Household register form submitted. Next time when Motech event trigger its works according to rule.

**Comment by cagulas** [comment]
Agree this is a pragmatic requirement from the FWAs.  Glad to hear a solution was already found.

@proshantokuet can you clarify practically what this will mean for FWA in the app?  Does this mean the PSRF form will be triggered immediately after HH Reg form is submitted?  Does it require an internet connection?  Thanks.

**Comment by sohelsarder** [comment]
@cagulas its simply putting new actions for the very first time avoiding MotechListener, but the subsequent activities definitely go through Motech. Yes at least a new sync requires after immediate action creation and that time you need INTERNET.

**Comment by cagulas** [comment]
Thanks @sohelsarder
