### ISSUE TITLE
StartTime EndTime format from form is not supporting in OpenMRS

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-server#108]
We are getting startTime and endTime in this format -
2016-01-26T12:23:07.000+06:00

But in OpenMRS, it doesn't allow GMT+6, so we are not getting values for these.

@sohelsarder @maimoonak @cagulas

**Comment by koros** [comment]
@sohelsarder please find out whether we need to use a specific format and also if need be, i think the issue can also be fixed at the client level while building the form submission

**Comment by sohelsarder** [comment]
@koros thats indeed would be good solution, in fact I have already asked raihan  to do so but he told me some sort of difficulties there so we have resolved it from server side.
if you guys can format it from client that would be perfect and benefit of all sites.

Currently coming from client: "2015-09-21T11:41:36.000+06:00"  expected Output:2015-09-21 11:41:36 that openmrs can accept in its date time concept without complaining.

**Comment by koros** [comment]
@sohelsarder alright thanks a lot, i'll implement the changes on the client side as well, do we have data currently on the server side that is already using the old format, because it means we may have two sets of data, one with the new format and the other with the other old format. i hope there is no side effect.

**Comment by raihan-mpower** [comment]
@koros in my knowledge,this format is something native to all xform technology, like odk , enketo etc. So if we were to change to anything in enketo date format , we would have to re implement the edits each time we upgrade enketo or if we even move to any other form technology that uses xforms. So each time we change we would have to make these edits. On the contrary having this on server side would mean one single point of change.

**Comment by koros** [comment]
@raihan-mpower Yeah i agree, but at the moment since we are taking the raw xml data that is obtained from Enketo form and then using that to build the form-submission it makes no difference i.e in future even if we move to ODK technology we'll still have to build the form-submission i.e as we are doing currently with the FormUtils.
So i was thinking we can do that transformation as we build the form-submission, looks like this step is inevitable for now, i.e whichever technology we choose none will give us the form-submission that ziggy can process directly we still have to build the form-submission ourselves.

**Comment by sohelsarder** [comment]
@koros It makes sense, XML to form-submission conversion no way of by passing irrelevant of clients platform technology (ODK/Enketo) you choose, if you stick with ziggy that is must. So formating during that conversion stage seems worthy.

**Comment by sohelsarder** [comment]
@koros/ @raihan-mpower : Also have you notice this issue i have raised,

https://github.com/OpenSRP/opensrp-server/issues/107. Can you please raise the implication of client if server introduce a new key at submission.

**Comment by koros** [comment]
Yeah @sohelsarder thats right, we'll exploit all these options

**Comment by koros** [comment]
@sohelsarder i have committed client side fix for this, see https://github.com/OpenSRP/opensrp-client/issues/146

**Comment by cagulas** [comment]
@sohelsarder The client side fix is already in place (see Koros' comment above), so we're waiting to hear whether a corresponding server side fix is needed, since there's already existing data.  Please let us know, thanks.

@numeranazneen

**Comment by sohelsarder** [comment]
@cagulas : Client fix working fine, I am going to wipe out server fixation then.

Thanks @koros  @raihan-mpower  for placing that in client.
