### ISSUE TITLE
openSRP server building and implementation for birth registration and death registration data integration with CRVS

### ISSUE THREAD

**Issue by asifur77** [OpenSRP/opensrp-server#126]
CRVS (Civil Registration and Vital Statistics) is a part of DGHS project.....the idea is when Child will be registered via OpenSRP, it'll get a temporary ID from CRVS system, the CRVS system will be integrated with NID (National ID) system. As you know that it took much time to provide NID to the citizen, so when NID will be assigned for that Child, it'll send that ID to OpenSRP via CRVS. Then the Child will be tagged with that NID in SRP. Similar kind of thing will happen for Citizen's Death Registration. For that we are planning to develop their Child Registration Form and integrate that with OpenSRP-Child Register.

**Comment by cagulas** [comment]
Thanks for the background. What is the necessity of the temporary ID from CRVS system? Does CRVS system already give out temporary IDs, or is this a new feature for OpenSRP child registrations?

**Comment by sohelsarder** [comment]
@cagulas : This is because the information and id's CRVS system taking from openSRP are not verified from openSRP side, there will be other work flow from CRVS side to verify and assign ID for newly register child (i.e their parents will go to UDC office show their ID's get verified from NID then take new ID for their newly born kids ). So this middle stage CRVS and openSRP will communicate via temporary ID.

**Comment by cagulas** [comment]
Ok, this is helpful, thanks.

So, CRVS system will allocate temporary ID to child when registered in OpenSRP, then when child goes to UDC office for verification and NID assignment, how will CRVS system look up the child's temporary ID from OpenSRP and assign the NID to the right child in OpenSRP?

Also, what happens when child does not get registered in OpenSRP till after NID is already assigned? Would the health worker simply enter the NID into the child registration form and temporary ID is not assigned?
