### ISSUE TITLE
Import script to import Ona data from PATH into OpenSRP

### ISSUE THREAD

**Issue by geoffreymuchai** [OpenSRP/opensrp-server#201]
The existing registration and vaccination data exists in the form of paper forms and so pictures of these forms will be taken and entered into a webform with the aim of importing this data into OpenSRP server

**Comment by cagulas** [comment]
@geoffreymuchai I've modified this issue title to reflect the new plan to write import scripts to import the PATH data from Ona into OpenSRP server.

**Comment by maina** [comment]
This code goes to a controller so that it's possible to launch this process from the browser. Initially we can work with a downloaded csv export from Ona but later on see if we can download the export automatically from Ona. The tasks involved are as follows:
- [ ] Create an endpoint(controller) for invoking this process in opensrp-web
- [ ] Client data processing - in the csv export all columns title that start with Childs_Particulars/ generally have child's demographic info. However, two clients are generated from this data; child and mother. Columns that have mother's details will generally have the prefix Childs_Particulars/Mother_Guardian. When creating these two documents remember to create a relationship to link a child to the mother. This is done by adding a 'mother' key in the child's document relationship key and setting the value as the mother's id. In this process, two events are created *Birth Registration* and *New Woman Registration*. The birth registration / new woman registration events have all the child's/mother's details that are not openmrs person* entity e.g Father_Guardian_Name, Birth_Weight for child.  For more information birth registration tab in the data dictionary excel- https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=0
- [ ] Automatically assign clients zeir_id - This involves downloading unique_ids from openmrs and assigning to clients as zeir_id. We can pull these in batches and store locally.
- [ ] Immunizations data processing- All immunization data is in the columns whose title has the prefix Immunisation_Record/. The suffix for these columns title is the vaccine name and if more than one vaccine were given on the same day the various vaccine names are separated by an underscore. This process creates a "Vaccination" event whereby the obs are the vaccines and the dates they were given or the dose. See an existing vaccination event in opensrp....
- [ ] Growth monitoring data processing - The csv will have 3 weight records and their dates for each client. The columns title for weight records will have the prefix Growth_Chart whereby for each weight record there will be two columns: Growth_Chart/weight* (the weight value),  Growth_Chart/weight*_date(date weight was taken). Each of this generates a new event -Growth monitoring
- [ ] Automatically download the export from Ona - may be..
- [ ] Unit and functional test to that all data is captured properly
*All events should have at least date, providerId, locationId, baseEntityId(from the client's doc), start, end ,deviceid*

**Comment by geoffreymuchai** [comment]
closed by cc3ab90
