### ISSUE TITLE
Error Handler and Logger

### ISSUE THREAD

**Issue by maimoonak** [OpenSRP/opensrp-server#42]
Parent #3 

Log event, event data, and error trace incase of failed POSTs. 
The error should also specify severity .

Components are
- Domain/model
- Repository
- Service

**Comment by ahmedihs** [comment]
Uploading snapshots of initial look of error Handlling . and its class diagram . please provide your feedback what other features should be added

![allerrors](https://cloud.githubusercontent.com/assets/11191881/8717378/6566b5bc-2bb4-11e5-9920-64f739cb20dd.PNG)
![viewerror](https://cloud.githubusercontent.com/assets/11191881/8717379/65677326-2bb4-11e5-963c-4d9131b06fa9.PNG)
![errortracediagram](https://cloud.githubusercontent.com/assets/11191881/8717390/94a505b8-2bb4-11e5-8a91-71a7e647cf73.jpg)

**Comment by maimoonak** [comment]
@ahmedihs please also list down the next steps (post to url for retry etc)

**Comment by ahmedihs** [comment]
this is an updated Error Handler . Now user can update the status . and perform retry functionality. 
Retry functionality can be used for different purposes like retrying form submission  for that particular form which wasnt pushed to openMRS successfully . the code has been already commit in Errorlogging branch . thanks
![Uploading allerrors-new.PNG…]()
![viewerror-new](https://cloud.githubusercontent.com/assets/11191881/9130403/d76f4fd6-3cfb-11e5-94da-b79b784139d9.PNG)

**Comment by ahmedihs** [comment]
![allerrors-new](https://cloud.githubusercontent.com/assets/11191881/9130479/75e371d8-3cfc-11e5-8f8e-55f03796e0b1.PNG)

**Comment by ndisha** [comment]
Hey @ahmedihs it seems your branch is missing some files from master - these were added last week. Please rebase with master since your branch is failing because of this. Let me know if you have any queries.

On the UI, I wish I could see this live and explore the functionality but a couple of comments:
* [ ] Can we have the menu (which has All Errors, Solved Errors and Unsolved Errors) move slightly lower? It's hiding part of the OpenSRP wording.
* [ ] What do we have under 'Options'?
* [ ] Can we add a detail column - that will have the detail of the error. Right now it just shows the name and am not sure how detailed this column will be so that we can see exactly what the error is.
* [ ] What other action can we expect under the Action column? For error/query management, I thought we would have some sort of flow where, an incoming error (reported by the system) is open by default, once its solved, it can be closed, and if it recurs, it can be reopened? On your Action column you have 2 options, retry and update? I could be wrong so please let me know what you intended to have under the Action column. 

Overall, it looks good! @koros @maimoonak @sohelsarder any ideas?

**Comment by sohelsarder** [comment]
Thanks, @ahmedihs, @maimoonak and team  these are some excellent steps and enhancement on opensmrs transmission error handling and make it transparent to user. Though i am unable to build and check the functionalities, i asked my developers to merge that work with our branch so that i can check the changes  with some real submissions . @ahmedihs, @maimoonak kindly ensure your other earlier fixation on openmrs connector also updated in 'error logging' as well.  @ndisha, @koros, and @cagulas do you guys have any  test plan of these enhancement and confirm the changes?

**Comment by ahmedihs** [comment]
Hi @ndisha , 
- yes menu can set to little lower .  
- Under Options , its only logout button but we can have other options  like searching between dates or searching errors of an particular date. 
- there are other detail informations , like Error type and document type . which  can be shown .
- basically update is only to update the status and where as retry is complete different . here developer have to define in code a url where this error information can go and could be retried again on that particular document . the URL' s functionality have to defined anywhere .

**Comment by ahmedihs** [comment]
@sohelsarder there were some files missing . i have added them .

**Comment by ndisha** [comment]
Thanks @ahmedihs for this - I am adding @euclidian to this conversation as he has extensive experience with https://raygun.io/features/all, @euclidian please add your ideas on this ticket.

**Comment by euclidian** [comment]
Practically, if we use raygun, we just send the exception to raygun server. We intercept all exceptions and push them to the cloud. Raygun already has its own dashboard to show it to us complete with its filter and other features. They also have email notification to push the exception to listed email.

**Comment by ndisha** [comment]
Thanks @euclidian; in view of what you have done with Raygun, please work with @ahmedihs to further refine what he is doing. Let me know if you need my help to coordinate this.

**Comment by maimoonak** [comment]
@ahmedihs Thanks for sharing the app for initial feedback. An initial assessment is below...
The data table thing look really cool and easy to use. UI is also very intuitive and user friendly.. Some points may need team feedback and further discussions so sharing the images here..

![1](https://cloud.githubusercontent.com/assets/4829880/9301261/88685fd4-44e6-11e5-92ff-c6eab03532fe.png)
![2](https://cloud.githubusercontent.com/assets/4829880/9301260/884419da-44e6-11e5-965d-51d86d2c7c75.png)
![3](https://cloud.githubusercontent.com/assets/4829880/9301259/884246a0-44e6-11e5-887c-849bd301250b.png)

**Comment by ahmedihs** [comment]
@maimoonak  
Page 1 : is a simple , it would be removed .

Page 2  Main page 

point 1 : this logo is modified . it can be shifted towards center.
point 2 : it will be removed
point 3 : i havenot complete idea why this is happening . i will try to figure out best of it.
point 4 : basically dropbox is provided because user from here can update the status . 
point 5 : date can be formatted easily 
point 6 : it can be resized
point 7 :  basically table doesnt refresh itself when update is performed but this functionality can be added.
point 8 : yes another seperator can be added.

**Comment by ahmedihs** [comment]
updated the UI and made Error Handler on Completely on single page.

**Comment by ndisha** [comment]
@ahmedihs so you mean you have incorporated the comments above and the work is now complete?

**Comment by ahmedihs** [comment]
@ndisha  it is completed . it is not merged with master branch . if there are any advice or changes  then so that would be added in it . please review it from your end . thanks

**Comment by ahmedihs** [comment]
![errorhandler-errorview](https://cloud.githubusercontent.com/assets/11191881/10809613/2f363a7c-7e1a-11e5-8f2f-49ff313ab5e0.PNG)
![errorhandler-view](https://cloud.githubusercontent.com/assets/11191881/10809612/2f3139a0-7e1a-11e5-8903-a2fc9caef933.PNG)
this are updated view of error handler

**Comment by koros** [comment]
@ahmedihs thanks will have a look at this then let you know if there are any issues

**Comment by koros** [comment]
Hi @ahmedihs i have checked out the commits, looks good, thanks for the good work.
A couple of issues though:
- When you click on "Solved Errors" an exception is thrown after an ajax call is made see the attached screenshot
<img width="1309" alt="screen shot 2015-10-30 at 2 11 00 pm" src="https://cloud.githubusercontent.com/assets/1716093/10844819/ee94bc5a-7f13-11e5-947c-05fc152b0709.png">

- The css looks a bit off on safari browser and the sets browser, i wonder if you had tested it on all the major browsers.
<img width="1311" alt="screen shot 2015-10-30 at 2 14 20 pm" src="https://cloud.githubusercontent.com/assets/1716093/10844855/33bdd988-7f14-11e5-8258-c9f8784bb2e4.png">

- The Error type box truncates long text messages(this is minor if it takes a lot of time to fix, you can ignore it since we already know the error type from the previous screen anyway)
<img width="622" alt="screen shot 2015-10-30 at 2 36 50 pm" src="https://cloud.githubusercontent.com/assets/1716093/10844892/8392fe66-7f14-11e5-9bc2-cba35ca217b0.png">

- The popover appears suddenly after some delay when the user clicks on "View StackTrace" we could show a progress bar or some indicator to show the user there is some action going on i.e at the moment one can easily click it twice.

**Comment by maimoonak** [comment]
@shakjaf110 please close this as well with reference to the issue this is resolved in

**Comment by shakjaf110** [comment]
see issue #43, this issue is resolved there.
