### ISSUE TITLE
OpenSRP to OpenMRS data transmission fixing the bugs and address all cases for house hold registration and census form submission.

### ISSUE THREAD

**Issue by sohelsarder** [OpenSRP/opensrp-server#77]
Hi everyone i was checking house hold registration and census form data transmission between openSRP to openMRS and my finding is current version of code don't address all scenarios of submission. It may be because it was base on some earlier assumptions that was not complete  scenarios.

I just identified following case that we need to handle from code base. Then it would be workable for all clients all scenarios.
case 1: new house hold  + single new woman in it
case 2: new house hold + 2 or more  new woman in it
case 3: new house hold + no new woman in it
case 4: Old house hold + + single new woman in it
case 5: old house hold + 2 or more  new woman in it

@maimoonak , @ndisha  can you please check these and test the scenarios on current development.

**Comment by ndisha** [comment]
@sohelsarder I have tested these scenarios, see my results below:
* [ ] case 1: new house hold  + single new woman in it - Pass
* [ ] case 2: new house hold + 3 new woman in it - Pass
* [ ] case 3: new house hold + no new woman in it - Fail (The data was not transmitted to OpenMRS)
I checked catalina.out and there is no error thrown on there, therefore am not sure what exception to report here. I remember when we talked about this @maimoonak said that the latest code of the openmrs connector handles empty repeat groups, @sohelsarder are you using the latest code?

* [ ] case 4: Old house hold + + single new woman in it and case 5: old house hold + 2 or more new woman in it
It was not possible to test these 2 scenarios since from the latest .apk that @raihan-mpower shared the ELCO register cannot be launched as a separate form until the 'HH visit due date' reaches; seems @julkarnain implemented the HH schedules already. I don't know the best way to test this out but the last time I tested it worked just fine.

**Comment by sohelsarder** [comment]
@ndisha  thanks for taking drive over it. yes i am checking with latest code from error logging branch and merged it with our mCare version.
did you checked with expected outcome i.e
case 1: expected outcome at openmrs is (2 person, 2 patient, 2 encounter)
case 2: expected outcome at openmrs is (4 person, 4 patient, 4 encounter)

**Comment by maimoonak** [comment]
@ndisha @sohelsarder ... This discussion and openmrs issues had been tested and discussed for long on possibly a branch that is older and doesnot have latest code. I have compiled a war file from master, updated the latest forms of HH and deployed on server. It looks fine for empty repeat and form multiple persons in HH.

Since master was not merged with julkar`s code it wont have HH, and HH schedules.
It may also have followup form issues, but it is working fine. 

Please do your testing now on the Ona serevr and let me know the issues in master repo so that we can get a sense of actually missing piece.

**Comment by numeranazneen** [comment]
@sohelsarder just FYI,  I tested the 3rd case ( zero MWRA) using ona server. I found one person and one patient for the HH Head, but didn't find any encounter for the HH Head. 

@ndisha @maimoonak

**Comment by maimoonak** [comment]
@numeranazneen could you please share an example person with such data. I tested and found both encounters created. Maybe you ae trying to find HHHead encounter in HHmember!!

**Comment by ndisha** [comment]
Hey @numeranazneen where are you looking for encounters? As @maimoonak says, I also just tested and its all good on my side, see the screenshot attached:

<img width="1253" alt="screen shot 2015-08-24 at 10 40 02 am" src="https://cloud.githubusercontent.com/assets/801106/9435041/e09189a4-4a4c-11e5-8a53-f5f8732b51c4.png">

Please share with us the example of your data since we are not able to recreate this problem.

**Comment by sohelsarder** [comment]
Hey @ndisha i just merged branch master, masterCloneforDemo and error logging branch and run the test, still census for submission case was missing there (case (4&5) above). I changed some code in openmrs-connector and  form submission controller. Now it can handle census  submission cases. The latest source in "external_system_integration" branch, this branch  contains scheduling code of House registry and census form scheduling + Elco registry and psrf scheduling and the developed service for external system integration. You may run a test to confirm the functionalities.

**Comment by sohelsarder** [comment]
Data transmission from openSRP to openMRS going smoothly.
