### ISSUE TITLE
openSRP login failed : interruption with openmrs authentication service 

### ISSUE THREAD

**Issue by numeranazneen** [OpenSRP/opensrp-server#93]
Hi, @ndisha / @cagulas   / @maimoonak 

We are not able to log into OpenSRP app because of OpenMRS authentication service failure. We have experienced this issue several times during testing, sometimes after few minutes it resumes to its normal state but sometimes it takes much long time. 

46.101.51.199:8080/openmrs/index.htm;jsessionid=E1384765D715A1

From yesterday evening,  we are not able to log into the app. We are not sure if you are getting the same problem or not. If so, then please fix this issue ASAP, because system stability is very much important to run this project in field. Thanks.

@sohelsarder

**Comment by mberg** [comment]
We will take a look. Thanks for reporting this

**Comment by ahmedihs** [comment]
Hi @numeranazneen  , 
                                 OpenMRS is now working , i have restarted the server.

**Comment by sohelsarder** [comment]
Hi @ahmedihs  thanks for your support, can we investigate the root cause of this incident? because earlier we experienced it several times,  we need to explore whether it is happening due to the resource constraint in server (i.e memory exhausted?) if it is the reason then need to find out what is / which module/ which operation are creating memory leakage? can we protect it from web sever (believe tomcat provides a way ). What is important is in new architecture of openSRP , openmrs service specially authentication need to be very stable other wise that will stopped total activities of openSRP.  I had set up our own instance of openmrs at Bangladesh for mCare operation but there also we fetched similar interruption sometimes   from our openmrs instance too.  We are looking forward to find out the  reason what is making openmrs service unstable.

**Comment by ndisha** [comment]
Thanks @ahmedihs! 
I was looking at why this is happening and from catalina.out, I get this consistent message:

INFO - HibernateContextDAO.authenticate(181) |2015-10-06 03:38:19,248| Failed login attempt (login=admin) - Invalid username and/or password: admin
WARN - AuthenticatedTask.authenticate(98) |2015-10-06 03:38:19,251| Error authenticating 'admin' user. Please ensure you scheduler username and password are configured correctly in your global properties

From this conversation, it sounds like there is a restrictions on any modules with scheduled tasks to have the same username/password in the global properties: https://groups.google.com/forum/#!msg/kenyaemr-developers/etBDWOywoAg/JuLCnCHXma0J

@cagulas and I have experienced this twice as well, where we were not able to log into OpenMRS for a while, then it allowed us after a server restart or sometimes just like that. 
Since @numeranazneen says it has happened many times as well for her and based on the conversation above, can we look for a permanent fix? Like the one suggested above?

**Comment by maimoonak** [comment]
@numeranazneen @sohelsarder @ndisha 

OpenMRS requires password reset after every x logins. We are using admin account for REST service access. I would change it tomorrow in deployed app and then test if it works fine.
Restart and memory issues occur when modules are deployed frequently for testing. This causes tomcat heap memory reach its limit In production server it wont happen. 
When problem is resolved immediately without server restart or password reset, it could be network connectivity issue.. Are you sure network connectivity was fine at that moment when issue resolved automatically immediately?

**Comment by maimoonak** [comment]
I have changed the username and password in instance deployed on Ona server. Hopefully it wont force change/rest pwd after few logins.
Please test the app and let me know if it has broken anything. Ideally it should keep working as before but changing default admin is a major change so it should be tested thoroughly.
